### ISSUE TITLE
import-sql failed for layer place

### ISSUE THREAD

**Issue by jpbede** [makina-maps/makina-maps#23]
When i'm trying to import the planet, the import-sql step fails with following error:

```CREATE FUNCTION
Time: 2.565 ms
psql:/sql/parallel/place.sql:757: ERROR:  LIKE pattern must not end with escape character
CONTEXT:  SQL function "update_osm_city_point" statement 1
Time: 5254.250 ms (00:05.254)
Makefile:358: recipe for target 'import-sql' failed
make: *** [import-sql] Error 123
```

Other layer-sql is imported without any error or problems.

**Comment by frodrigo** [comment]
It looks like with an issue on this https://github.com/frodrigo/openmaptiles/blob/6e26c75e9659794a06b7b1862c68010511fe38ca/layers/place/update_city_point.sql#L24-L34

It come from OpenMapTiles pristine code.

The code relies on OSM content from LIKE operation, it may contain somewhere in the planet invalid data for this.

Need further check, but the OSM name should probably be sanitized.

**Comment by jpbede** [comment]
This seems to work for me:

```
ne.name ILIKE replace(osm.name, '\', '\\') OR
ne.name ILIKE replace(osm.name_en, '\', '\\') OR
ne.namealt ILIKE replace(osm.name, '\', '\\') OR
ne.namealt ILIKE replace(osm.name_en, '\', '\\') OR
ne.meganame ILIKE replace(osm.name, '\', '\\') OR
ne.meganame ILIKE replace(osm.name_en, '\', '\\') OR
ne.gn_ascii ILIKE replace(osm.name, '\', '\\') OR
ne.gn_ascii ILIKE replace(osm.name_en, '\', '\\') OR
ne.nameascii ILIKE replace(osm.name, '\', '\\') OR
ne.nameascii ILIKE replace(osm.name_en, '\', '\\') OR
```

There are 3 city points with a \ in the end:

![image](https://user-images.githubusercontent.com/3989428/89382760-a31ddc80-d6fb-11ea-9ae8-4023071aa227.png)

**Comment by frodrigo** [comment]
It seam to me the `ILIKE` is just here for case insensitive comparison, it is a bad idea.
Comparing lower case version using `lower()` look to me to be the right thing to do.
I will try to make an OpenMapTiles PR about this.

**Comment by frodrigo** [comment]
PR in https://github.com/openmaptiles/openmaptiles/pull/961

**Comment by jpbede** [comment]
Great, thank you :)

**Comment by jpbede** [comment]
PR was merged. So i'm closing this. Thanks for your help :)

**Comment by frodrigo** [comment]
Do you want a backend port of this fix ?

**Comment by jpbede** [comment]
Yea would be great but not necessarily. Already fixed it locally

**Comment by frodrigo** [comment]
It's done.

Note Makina Maps and patched OpenMapTiles are now both under the makina-maps github organisation.
