### ISSUE TITLE
What is the behavior on OSM updates

### ISSUE THREAD

**Issue by boldtrn** [makina-maps/makina-maps#28]
Sorry, I haven't tested this yet. What is the behavior on updates. For example if I'd use the planet file with 24hr or 48hr update frequency, what happens during the updates? Is the database frozen during that time or can tiles still be generated (but maybe a bit slower)?

**Comment by frodrigo** [comment]
The service of tiles is not frozen during the update (unlike the current OpenMapTiles master version).

**Comment by boldtrn** [comment]
Thanks for the explanation :)
