### ISSUE TITLE
Some polygons are missing

### ISSUE THREAD

**Issue by pyrog** [makina-maps/makina-maps#35]
See https://github.com/vdct/ProjetDuMois/issues/112#issuecomment-751259507

**Comment by pyrog** [comment]
* https://www.openstreetmap.org/way/240205297
* https://www.openstreetmap.org/way/251413492
* https://www.openstreetmap.org/way/251417476
* https://www.openstreetmap.org/way/251413614
* https://www.openstreetmap.org/way/360231933
* https://www.openstreetmap.org/relation/11634124
* https://www.openstreetmap.org/relation/11634124
* https://www.openstreetmap.org/relation/974821
* https://www.openstreetmap.org/way/62528160
* https://www.openstreetmap.org/way/62527967

**Comment by frodrigo** [comment]
Duplicate #30
