### ISSUE TITLE
openmaptiles-tools either does not exist

### ISSUE THREAD

**Issue by l-longour** [makina-maps/makina-maps#52]
When I run the script `../scripts/10-import-generic.sh` from the openmaptiles folder as indicated on the readme, this error appears. 
 
```
ERROR: build path /home/lucas/makina-maps/openmaptiles/openmaptiles-tools either does not exist, is not accessible, or is not a valid URL.
```
I consciously followed the instructions of the readme.

The `docker-compose pull` command seems to have worked correctly since all the images appear well on my portainer. I guess it can't be much but I'm stuck on it.

**Comment by frodrigo** [comment]
I do a new fresh install from scratch and all works well.
`makina-maps/openmaptiles/openmaptiles-tools` is not a required path as `openmaptiles-tools` is on a docker image.

**Comment by amenk** [comment]
I actually got the same problem today. `git checkout master` in the openmaptiles folder seemed to help. Is the submodule link maybe outdated?

**Comment by amenk** [comment]
@frodrigo it was required here: https://github.com/makina-maps/openmaptiles/commit/cd0d801257c10e2416923d7c6604510abbb4fdfa#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

and still seems to be in the linked openmaptiles revision: https://github.com/makina-maps/openmaptiles/blob/69a53b106e45eb1b37ecf719cd57721bf4dab23a/docker-compose.yml#L30

**Comment by amenk** [comment]
@frodrigo Is it possible that something is broken here / was not fully pushed or the submodule link not updated?

**Comment by amenk** [comment]
I think this branch / fork was used there

https://github.com/makina-maps/openmaptiles-tools/tree/custom_imposm

It used a patched imposm which is related to this issue:

https://github.com/omniscale/imposm3/issues/262

**Comment by frodrigo** [comment]
Yes you are right all along the line.

**Comment by amenk** [comment]
@frodrigo do you plan to remove the patch? I think currently the setup does not work for (some, at least for me) according to the setup instructions because of this.

**Comment by frodrigo** [comment]
OpenMapTiles is now up to date.
