### ISSUE TITLE
NGINX to work on secure 443 port with Certbot

### ISSUE THREAD

**Issue by benjonesqueens** [makina-maps/makina-maps#57]
I think your project is great, the only drawback i can see is to use in a production environment is make use of certbot to obtain SSL certs

example like
https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose

Just a thought

Ben

**Comment by frodrigo** [comment]
The simplest way is to use http server outside docker with reverse proxy and with SSL certs.
