### ISSUE TITLE
Raster tiles not loading

### ISSUE THREAD

**Issue by amenk** [makina-maps/makina-maps#59]
I followed the setup instructions and imported Ethiopia from OSMFR, having a 40-update.sh running.

Vector tiles work well and are rendered fast (50-500ms)

But the raster tiles are timing out after one minute:

Example URL: http://localhost:8080/styles/bright/16/39832/31127.png

Docker log from the makina maps containers:

```
nginx_1          | 2022/02/19 08:16:40 [error] 10#10: *184 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.23.0.1, server: nginx, request: "GET /styles/bright/16/39832/31124.png HTTP/1.1", upstream: "http://172.23.0.5:80/styles/bright/16/39832/31124.png", host: "localhost:8080", referrer: "http://127.0.0.1:8080/"
nginx_1          | 172.23.0.1 - - [19/Feb/2022:08:16:40 +0000] "GET /styles/bright/16/39832/31124.png HTTP/1.1" 504 569 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
tileserver-gl_1  | GET /styles/bright/16/39832/31124.png - - - - ms
```

I also did 

```
openmaptiles$ docker-compose logs -f
```

here nothing is displayed when accessing that tile (for vector tile access I am getting output)

* Which rendering times are expected for raster tiles (as compared to vector tiles)?
* How can I debug this further?

**Comment by frodrigo** [comment]
Raster tiles are rendered from vector tiles. So longer.

Rester tile should not be disabled on tileserver gl config. Look at its docs.

I will check and debug this latter.

**Comment by amenk** [comment]
okay, I did not change https://github.com/makina-maps/makina-maps/blob/6a57345077bc7059275451ba490cb6063b66e124/tileserver-gl/config.json#L24 - actually I put an additional

      "serve_rendered": true,

into the "bright" style just in case, but it is also not working.

**Comment by goody85** [comment]
Rasters dont work on dev2-makinamaps.makina-corpus.net also?

**Comment by frodrigo** [comment]
Tileserver-gl does not render raster tiles at this time.

```
makina-maps-tileserver-gl-1  | GET /styles/bright/3/5/1.png - - - - ms
```

There is log of timeout. For now, no idea why.

**Comment by frodrigo** [comment]
The code was not functional. Not finished yet.
So, I make it works!

**Comment by frodrigo** [comment]
Strange, because there are not totaly blank.
Maybe lower vector tile zoom are used, because tile take too long to generate or something else.

**Comment by amenk** [comment]
I imported Ethiopia only, but the vector tiles at least the outlines of the other countries. but wherever I zoom to Overview: (http://127.0.0.1:8080/#map=2.78/33.1/12.08&style=bright) or Ethiopia: http://127.0.0.1:8080/#map=11.26/8.9615/38.76&style=bright it's all only yellow, empty tiles.

Is this a known issue?

**Comment by frodrigo** [comment]
> I imported Ethiopia only, but the vector tiles at least the outlines of the other countries. but wherever I zoom to Overview: (http://127.0.0.1:8080/#map=2.78/33.1/12.08&style=bright) or Ethiopia: http://127.0.0.1:8080/#map=11.26/8.9615/38.76&style=bright it's all only yellow, empty tiles. Vector tiles work well.
> 
> Besides BORDER_CLEANUP=true I did not make any changes to the default configuration.
> 
> Is this a known issue?

This issue was about raster tiles.
It looks like you have no OSM data. Check the data, or redo the full import process.

**Comment by amenk** [comment]
But the vector tiles are fine, only raster tiles are empty

**Comment by amenk** [comment]
I followed the README again, this time for Andorra and I have the same problem. The raster tiles only have the background color, while vector tiles are working fine.

I tried do debug a bit, and understand, that the vector tiles are served directly, not via tileserver-gl, so the problem might be that tileserver-gl cannot access the map data. But in the postgres database, the OSM data is there, otherwise I guess the vector tiles work also not work.

**Comment by frodrigo** [comment]
I think it is not clear in the README. Do you make this configuration step: https://github.com/makina-maps/makina-maps#public-urls

**Comment by amenk** [comment]
Ah, no I did not make any config changes. In fact I am on localhost (my laptop), not yet a public server. So I think the tileserver container cannot access the default http://localhost:8080 ?

**Comment by frodrigo** [comment]
> Ah, no I did not make any config changes. In fact I am on localhost (my laptop), not yet a public server. So I think the tileserver container cannot access the default http://localhost:8080 ?

No, since the localhost is inside the docker. It is not you "local" host.

**Comment by amenk** [comment]
So maybe something like "nginx" might work? Have to try... Or I can use my DNS name in the LAN of course

**Comment by amenk** [comment]
http://nginx/ works ... will make a PR

**Comment by frodrigo** [comment]
> http://nginx/ works ... will make a PR

Not. It does not work because this URL is exposed to the web for direct vector tile access. `nginx` is only know from within the docker network. It will work only for the raster.

**Comment by amenk** [comment]
Yep, I was wrong :-) https://github.com/makina-maps/makina-maps/pull/61#issuecomment-1113955027
