### ISSUE TITLE
Cache invalidation not working / EXPIRE returns 405, method not allowed

### ISSUE THREAD

**Issue by amenk** [makina-maps/makina-maps#60]
I am testing the cache invalidation.

As I understand it, when `../40-update.sh` is running and I edit OSM data, after some minutes I should be able to Ctrl+F5 the makina maps page and the changes should appear there.

For testing I am doing (legimate) improvements in Addis Ababa. Mostly I am adding buildings, but I thought the problem might be related with #30 (even this is supposed to be fixed), so I also did some POI edits.

Here I removed an outdated POI:

https://www.openstreetmap.org/node/677510167

Also I disabled the browser cache.

When loading the map in the docker-compose log I see

```
nginx_1          | 172.23.0.1 - - [19/Feb/2022:11:47:22 +0000] "GET /data/v3/14/9956/7781.pbf HTTP/1.1" 200 126938 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"
```

This tile was invalided before, as I can see in the logs, when the change was populated with the updater:

```
nginx_1          | 127.0.0.1 - - [19/Feb/2022:11:44:17 +0000] "EXPIRE /v3/14/9956/7781* HTTP/1.1" 405 157 "-" "curl/7.79.1"
```

Response code 405 is method not allowed, so something seems wrong at this place.

Even with

```
NGINX_DISABLE_CACHE=1 docker-compose up
```

I am getting outdated data

I checked the database

```
select * from osm_poi_point where osm_id =  677510167
```

is giving zero results, so I believe it's a problem with the invalidation itself, not the database updating.

I will try to debug this further.

**Comment by amenk** [comment]
I was mixing things here, the last test was with NGINX_DISABLE_CACHE=1 which seems to disable the `EXPIRE` method as well, because of https://github.com/makina-maps/makina-maps/blob/6a57345077bc7059275451ba490cb6063b66e124/nginx/nginx.template.conf#L131

I will do more testing

**Comment by amenk** [comment]
Same result if I leave `NGINX_DISABLE_CACHE` out or remove that if clause in the template.
Unfortunately using the nginx-debug binary in `run.sh` switching to debug logging (`error_log /var/log/nginx/error.log debug;`) did not reveal much more information.

If I delete the nginx-cache volume and start everything again + hard refresh in the browser, it is working.

So I think this seems to confirm my theory, that the NGINX expiry / invalidation is not working.

**Comment by amenk** [comment]
I was trying to debug that a bit, even compiling NGINX with debug symbols and using `gdb` :-)
Wondering if this was ever working?

Which return codes do others get when doing a something like inside the nginx container (`docker-compose exec nginx /bin/bash`)

`curl -X EXPIRE "http://localhost:81/v3/14/9956/7781*"`

`curl -X EXPIRE "http://localhost:81/v3/14/9956/7781.pbf"`

?

I am always getting a 405 response code. Wondering if that just means, that there is nothing in the cache or that something is wrong.

**Comment by frodrigo** [comment]
I changed the nginx expiration module... and I introduced this issue.

I just push a commit to review that.

**Comment by amenk** [comment]
Nice

**Comment by amenk** [comment]
Just to confirm that I tested this with the latest commits and it's working now. 

Buildings mapped -> wait a minute / check the updater logs -> press F5 in the Makina maps demo -> buildings appear

Thank you very much! :tada:
